systemType: client

# !! IMPORTANT: this folder will be mirror copied. make sure it does not contain important files!!
clientVideosDir: D:\videos\vids
videosDeleteDir: D:\videos\delete

workspaceDir: E:\anisync-transfer

clientAnilogFile: D:\videos\vids.log